server:
  port: 8082

spring:

  application:
    name: hotels
  messages:
    encoding: UTF-8


  liquibase:
    url: jdbc:postgresql://localhost:5432/hotels
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
    user: postgres
    password: rootpassword
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hotels
    username: postgres
    password: rootpassword




#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hotels?currentSchema=public
#    username: postgres
#    password: rootpassword



